### ISSUE TITLE
Alchemy not possible to interact with the furnace

### ISSUE THREAD

**Issue by Bastiancococo** [ThatGuyGW/RoadToReincarnationEnglishMod#1]
[Player.log](https://github.com/ThatGuyGW/RoadToReincarnationEnglishMod/files/11225037/Player.log)
[Player-prev.log](https://github.com/ThatGuyGW/RoadToReincarnationEnglishMod/files/11225038/Player-prev.log)

**Comment by seelebrn** [comment]
Same as #2 
Fixed !
