### ISSUE TITLE
Alchemy not working

### ISSUE THREAD

**Issue by Berathen** [ThatGuyGW/RoadToReincarnationEnglishMod#2]
When getting to main quest, to use Alchemy furnace pressing the interact key wont bring up any interface. Logs attached.
[LogOutput.log](https://github.com/ThatGuyGW/RoadToReincarnationEnglishMod/files/11225047/LogOutput.log)
[ErrorLog.log](https://github.com/ThatGuyGW/RoadToReincarnationEnglishMod/files/11225048/ErrorLog.log)

**Comment by Berathen** [comment]
Tested without mod, can use furnace without translation.

**Comment by Berathen** [comment]
Can confirm if using the translation, then deleting the metadata in "\Steam\steamapps\common\轮回修仙路\轮回修仙路_Data\il2cpp_data\Metadata", and verify the integrity, you can interact with furnace.

**Comment by Berathen** [comment]
Trigerring this issue:
Download game
Insert translation
Start game
Generate character
Start the game
Alchemy/Refining interface wont be brought up, if equipment sprites do not exist

How to resolve (thanks to Cadenza)
When translation is already inserted, delete the metadata in "\Steam\steamapps\common\轮回修仙路\轮回修仙路_Data\il2cpp_data\Metadata", and verify the integrity, you can interact with furnace.

**Comment by Berathen** [comment]
Using this method will cause equipment to not be translated (refer to attached picture)
![bug](https://user-images.githubusercontent.com/19586760/231859766-d6280ed9-15ed-410f-84a9-08977e88e00c.png)

**Comment by seelebrn** [comment]
Fixed in the latest build ! 
The issue was a line in global-metadata.dat which shouldn't have been translated.
For reference, it was :  108816=Alchemy
This text is also not translated anymore on-screen (when you face the furnace and must press "e"), but I'll try to find another way to translate it. Later.
