### ISSUE TITLE
Cannot interact with shopkeeps/sect decans

### ISSUE THREAD

**Issue by Berathen** [ThatGuyGW/RoadToReincarnationEnglishMod#5]
With [v1.1.0.0](https://github.com/ThatGuyGW/RoadToReincarnationEnglishMod/releases/tag/Stable-1.1.0.0) cannot interact with shopkeeps. The interface does not come up

**Comment by seelebrn** [comment]
Could you confirm it's fixed with the latest build ?

**Comment by Berathen** [comment]
Tested with [v1.1.2.0](https://github.com/ThatGuyGW/RoadToReincarnationEnglishMod/releases/tag/Patch-v1.1.2.0) it works
